project:
  type: website
  output-dir: _site
  resources:
    - sitemap.xml

website:
  title: "Scott I. Donaldson, PhD"
  site-url: https://www.scottdonaldsonphd.com
  description: "Official website of Dr. Scott I. Donaldson"
  google-analytics: "G-66J1CSNLDK"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: Teaching.qmd
        text: Teaching
      - href: DMP.qmd
        text: Donaldson Measurement Partners
      - href: Contact.qmd
        text: Contact 
format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
          <link href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css" rel="stylesheet">

editor: visual

